[package]
name = "sokoban-rs"
version = "0.1.0"
edition = "2021"

authors = ["ShenMian <sms_school@outlook.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4"
nalgebra = "0.32"

bevy = "0.12"
bevy_editor_pls = "0.7"
rusqlite = { version = "0.30", features = ["bundled"] }
siphasher = "1.0"
arboard = "3.3"                                         # 系统剪切板
image = "0.24"
winit = "0.28"                                          # 版本需要与 bevy 中使用的保持一致

[profile.dev.package."*"]
opt-level = 3
