[package]
name = "soukoban-rs"
version = "0.1.16"
edition = "2021"

authors = ["ShenMian <sms_school@outlook.com>"]
license = "MIT OR Apache-2.0"
description = "A sokoban with solver."
repository = "https://github.com/ShenMian/sokoban-rs"
keywords = ["sokoban", "sokoban-solver"]
categories = ["games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soukoban = { git = "https://github.com/ShenMian/soukoban" }
bitflags = "2.4"
nalgebra = "0.32"
itertools = "0.13"
siphasher = "1.0"

leafwing-input-manager = "0.13"
bevy_kira_audio = "0.19"
benimator = "4.1"

serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.31", features = ["bundled"] }
arboard = "3.3"                                         # System clipboard
image = "0.25"
toml = "0.8"

winit = "0.29" # The version needs to be consistent with the one used in bevy

[dependencies.bevy]
version = "0.13"
default-features = false
features = ["multi-threaded", "png", "x11", "default_font"]

[profile.dev.package."*"]
opt-level = 3
