name: Test

on: [pull_request, push]

env: 
  CARGO_TERM_COLOR: always

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Update Rust
        run: rustup update stable

      - name: Install dependencies
        run: sudo apt install librust-alsa-sys-dev libudev-dev

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --no-cfg-coverage --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true